# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 521cc3987e96ca73cd30759d5a35777666a41f5a4398b2ff9b2074576ceaad5287a9ec7b5b49d4c7fad7d09802da248e48e2e68d91a470318325ab49230a2c45

test:
  secret_key_base: f65fb1556421bec05fb2e7e3df41edd261c17c2617e2ce0b5e9500910251fd963e75db3ab305dc4f5f3000808505f4b8557885639e5314e2abe6c0a35baeaed7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
